before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - main: ./cmd/keel
    id: "keel"
    binary: keel
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X 'github.com/teamkeel/keel/runtime.Version={{.Version}}' -X 'github.com/teamkeel/keel/cmd.enabledDebugFlags=false'
  - main: ./deploy/lambdas/runtime/cmd
    id: "runtime-lambda"
    binary: runtime-lambda
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w -X 'github.com/teamkeel/keel/runtime.Version={{.Version}}'
archives:
  - id: keel
    builds:
      - keel
    name_template: "keel_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  - id: runtime-lambda
    builds:
      - runtime-lambda
    name_template: "runtime-lambda_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
release:
  github:
    owner: teamkeel
    name: keel
  mode: append
  prerelease: true
checksum:
  name_template: "checksums.txt"
