# Run the following to set up the database instance use for tests:
#    docker compose up -d
# Run the following to also provision Jaeger for local tracing:
#    docker compose --profile tracing up -d

services:
  postgres:
    image: pgvector/pgvector:pg15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=keel
    ports:
      - "8001:5432"

  jaeger:
    image: jaegertracing/all-in-one:1.45
    restart: always
    profiles: [tracing]
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "9411:9411"
