services:
  postgres:
    image: pgvector/pgvector:pg15
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=functions-runtime
    ports:
      - "7654:5432"
